name: All Detections To Elastic

on:
  push:
    path:
      - '**.toml'
  workflow_dispatch:

jobs:
  toml-validation:
    env:
        ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
            python-version: '3.11.4'

      - run: pip install requests
      - run: python development/toml_to_json.py
