name: Updating Detections

on:
  push:
    path:
      '**.toml'
  workflow_dispatch:

jobs:
  elastic-detections-update:
    env:
        ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'  

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
      
      - name: Run Update Script
          env:
            ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}
            CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          run: |
            pip install requests
            python development/update_alert.py